-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-05-24 22:32:44 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE country (
    country_name VARCHAR2(50) NOT NULL
);

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( country_name );

CREATE TABLE human (
    human_id       INTEGER NOT NULL,
    human_name     VARCHAR2(50),
    human_gender   VARCHAR2(6)
);

ALTER TABLE human
    ADD CHECK ( human_gender IN (
        'female',
        'male'
    ) );

ALTER TABLE human ADD CONSTRAINT human_pk PRIMARY KEY ( human_id );

CREATE TABLE human_insurance (
    human_id           INTEGER NOT NULL,
    insurance_agency   VARCHAR2(50) NOT NULL,
    insurance_type     VARCHAR2(50) NOT NULL
);

ALTER TABLE human_insurance
    ADD CONSTRAINT human_incurance_pk PRIMARY KEY ( human_id,
                                                    insurance_agency,
                                                    insurance_type );

CREATE TABLE human_trip (
    human_id       INTEGER NOT NULL,
    trip_date      DATE NOT NULL,
    country_name   VARCHAR2(50) NOT NULL
);

ALTER TABLE human_trip ADD CONSTRAINT human_trip_pk PRIMARY KEY ( human_id,
                                                                  trip_date );

CREATE TABLE insurance (
    insurance_agency   VARCHAR2(50) NOT NULL,
    insurance_type     VARCHAR2(50) NOT NULL
);

ALTER TABLE insurance ADD CONSTRAINT insurance_pk PRIMARY KEY ( insurance_agency,
                                                                insurance_type );

ALTER TABLE human_insurance
    ADD CONSTRAINT human_incurance_human_fk FOREIGN KEY ( human_id )
        REFERENCES human ( human_id );

ALTER TABLE human_insurance
    ADD CONSTRAINT human_incurance_insurance_fk FOREIGN KEY ( insurance_agency,
                                                              insurance_type )
        REFERENCES insurance ( insurance_agency,
                               insurance_type );

ALTER TABLE human_trip
    ADD CONSTRAINT human_trip_country_fk FOREIGN KEY ( country_name )
        REFERENCES country ( country_name );

ALTER TABLE human_trip
    ADD CONSTRAINT human_trip_human_fk FOREIGN KEY ( human_id )
        REFERENCES human ( human_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                             10
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
